LabeledAsserts.dfy(25,11): Error: assertion violation
LabeledAsserts.dfy(27,18): Error: assertion violation
LabeledAsserts.dfy(28,18): Error: assertion violation
LabeledAsserts.dfy(29,15): Error: assertion violation
LabeledAsserts.dfy(32,11): Error: assertion violation
LabeledAsserts.dfy(162,17): Error: assertion violation
LabeledAsserts.dfy(172,15): Error: assertion violation
LabeledAsserts.dfy(189,19): Error: assertion violation
LabeledAsserts.dfy(193,13): Error: assertion violation
LabeledAsserts.dfy(16,11): Error: assertion violation
LabeledAsserts.dfy(42,18): Error: assertion violation
LabeledAsserts.dfy(43,13): Error: assertion violation
LabeledAsserts.dfy(91,13): Error: assertion violation
LabeledAsserts.dfy(105,13): Error: assertion violation
LabeledAsserts.dfy(107,13): Error: assertion violation
LabeledAsserts.dfy(128,15): Error: assertion violation
LabeledAsserts.dfy(142,19): Error: assertion violation
LabeledAsserts.dfy(146,13): Error: assertion violation
LabeledAsserts.dfy(206,20): Error: assertion violation
LabeledAsserts.dfy(207,15): Error: assertion violation
LabeledAsserts.dfy(211,15): Error: assertion violation
LabeledAsserts.dfy(224,20): Error: assertion violation
LabeledAsserts.dfy(226,11): Error: assertion violation
LabeledAsserts.dfy(232,11): Error: assertion violation
LabeledAsserts.dfy(252,6): Error: the calculation step between the previous line and this line might not hold
LabeledAsserts.dfy(265,9): Error: assertion violation

Dafny program verifier finished with 11 verified, 26 errors
